services:
  app:
    build:
      context: .
      target: production
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf:ro
      - cert_data:/etc/letsencrypt
      - cert_www:/var/www/certbot
    networks:
      - web-net

  certbot:
    image: certbot/certbot:latest
    volumes:
      - cert_data:/etc/letsencrypt
      - cert_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - web-net

volumes:
  cert_data:
  cert_www:


networks:
  web-net:
